CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL
);

CREATE TABLE "level_courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "description" varchar(500) NOT NULL,
  "level_id" int NOT NULL,
  "category_id" int NOT NULL
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL,
  "email" varchar(30) NOT NULL,
  "password" varchar(30) NOT NULL,
  "age" int NOT NULL,
  "rol_id" int NOT NULL
);

CREATE TABLE "users_courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "course_id" int NOT NULL
);

CREATE TABLE "courses_videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "url" varchar(30) NOT NULL,
  "course_id" int NOT NULL
);

ALTER TABLE "users_courses" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "users_courses" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "courses_videos" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("rol_id") REFERENCES "roles" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("level_id") REFERENCES "level_courses" ("id");


INSERT INTO categories (name) VALUES 
  ('Foundations'),
  ('Front-End Dev with React'),
  ('Node.js');

INSERT INTO level_courses (title) VALUES 
  ('Beginner'),
  ('Intermediate'),
  ('Advanced');

INSERT INTO roles (name) VALUES 
  ('Students'),
  ('Teachers'),
  ('Admins');

INSERT INTO courses (title, description, level_id, category_id) VALUES 
  ('Welcome to Foundations', 'In foundations we are gonna learn how program using HTML, CSS and Javascript', 1, 1),
  ('Welcome to React', 'In React we are gonna build apps and web sites.', 2, 2),
  ('Welcome to Node.js', 'In Node we are gonna learn how backend works', 3, 3);

INSERT INTO users (name, email, password, age, rol_id) VALUES 
  ('Fabrizzio Heredia', 'fabry@academlo.com', 26,'1003706711', 1),
  ('Steven Contreras', 'steven@academlo.com', 27,'1723479111', 2),
  ('Jesús Perez', 'elYisus@academlo.com', 42,'1708642444', 3);

INSERT INTO courses_videos (title, url, course_id) VALUES 
  ('Foundations 1', 'URL course 1', 1),
  ('React 1', 'URL course 2', 2),
  ('NodeJs 1', 'URL course 3', 3);

INSERT INTO users_courses (user_id, course_id) VALUES 
  (1, 1),
  (2, 2),
  (3, 3);

  